# Generated by Django 5.2.6 on 2025-09-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gr8tutor', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttutorrelationship',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
