# Generated by Django 5.2.6 on 2025-09-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gr8tutor', '0003_alter_studenttutorrelationship_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttutorrelationship',
            options={'ordering': ['-is_active', 'tutor__user_profile__user__username']},
        ),
    ]
