# Generated by Django 5.2.6 on 2025-10-20 09:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gr8tutor', '0004_alter_studenttutorrelationship_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('tutor', 'Tutor'), ('student', 'Student')], default='', max_length=10, null=True),
        ),
    ]
