# Generated by Django 5.2.6 on 2026-01-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gr8tutor', '0005_tutor_experience_alter_tutor_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time']},
        ),
    ]
